Repository alkemyTech/OT226-Server, pull requests merged in 2022-06, with the labels that each got.

#1 [UPDATES] deleting old models
  .env.example
  .eslintignore
  .eslintrc.js
  .github/workflows/node.js.yml
  .sequelizerc
  app.js
  bin/www
  config/config.example.js
  config/config.js
  controllers/index.js
  helpers/catchAsync.js
  helpers/error.js
  helpers/success.js
  middlewares/index.js
  migrations/20200921070147-create-role.js
  migrations/20200921211634-create-user.js
  models/index.js
  models/role.js
  models/user.js
  package-lock.json
  package.json
  routes/index.js
  routes/users.js
  schemas/index.js
  seeders/20201109013158-create-roles.js
  seeders/20201109013159-create-demo-user.js
  services/index.js
Labels: updates

#14 [ENDPOINT] OT226-23 - Create GET endpoint for organization public data.
  controllers/organizations.js
  helpers/success.js
  routes/index.js
  routes/organization.js
  services/organization.js
Labels: endpoint

#23 [FIX] New Model
  database/migrations/20220618150230-create-new.js
  database/models/new.js
Labels: fix

#25 [ENDPOINT] /POST News OT226-47
  controllers/news.js
  database/migrations/20220618150230-create-new.js
  database/models/new.js
  helpers/handleValidator.js
  middlewares/validator.js
  package.json
  routes/index.js
  routes/news.js
  schemas/new.js
  services/news.js
Labels: endpoint

#29 [OT226-33] - Endpoint delete user
  controllers/users.js
  routes/users.js
  services/users.js
Labels: endpoint

#31 [ENDPOINT] OT226-43 POST /categories
  controllers/categories.js
  controllers/users.js
  database/migrations/20220617013229-create-category.js
  database/migrations/20220617060403-create-testimonial.js
  database/migrations/20220617183415-create-user.js
  database/migrations/20220618150230-create-new.js
  database/migrations/20220618164317-create-activity.js
  database/migrations/20220618180105-create-organization.js
  database/migrations/20220620220459-create-member.js
  database/migrations/20220620222644-create-role.js
  routes/categories.js
  routes/users.js
  schemas/category.js
  services/categories.js
  services/users.js
Labels: endpoint

#37 [ENDPOINT] DELETE /news/:id
  controllers/news.js
  routes/news.js
  services/news.js
Labels: endpoint

#46 [MIDDLEWARE] OT226-27 validate admin
  middlewares/autetication.js
  middlewares/isAdmin.js
Labels: middleware

#58 [ENDPOINT] Put /organization/public/:id OT226-38- Update Organization
  controllers/organizations.js
  routes/organization.js
  schemas/organization.js
  services/organization.js
Labels: endpoint

#64 [UPDATE] OT226-51 Return the token to the user after registering on the site
  services/users.js
Labels: updates

#67 [ENDPOINT] - OT226-57 - Get /slides
  controllers/slides.js
  routes/index.js
  routes/slides.js
  services/slides.js
Labels: endpoint
