Repository alkemyTech/OT226-Server, pull requests merged in 2022-07, with the labels that each got.

#73 [ENDPOINT] Delete /slides/:id - OT226-61
  controllers/slides.js
  routes/slides.js
  services/slides.js
Labels: endpoint

#71 [FIX] OT226-51 Return the token to the user after registering on the site
  controllers/users.js
  helpers/success.js
  services/users.js
Labels: fix

#75 [ENDPOINT] OT226-60 Update slides by id
  controllers/slides.js
  routes/slides.js
  services/slides.js
Labels: endpoint

#77 [ENDPOINT] OT226-62 Add Slides to public endpoint
  controllers/organizations.js
  services/slides.js
Labels: endpoint

#76 [update] OT226-67 Modify organizations public endpoint
  services/organization.js
Labels: updates

#81 [endpoin] OT226-72 Endpint members get
  controllers/members.js
  routes/members.js
  services/members.js
Labels: endpoint

#83 [ENDPOINT] OT226-74 Add Endpoint Creation Members - POST /members
  controllers/members.js
  routes/members.js
  schemas/member.js
  services/members.js
Labels: endpoint

#87 [SEED] OT226-77 Create user seed
  README.md
  database/seeders/20220629013806-users.js
Labels: documentation

#85 [ENDPOINT] OT226-70 Update testimonials /testimonials/:id
  controllers/testimonials.js
  routes/index.js
  routes/testimonials.js
  schemas/testimonial.js
  services/testimonials.js
Labels: endpoint

#88 [ENDPOINT] OT226-76 Add Endpoint Update Members - PUT /members/id
  controllers/members.js
  routes/members.js
  services/members.js
Labels: endpoint

#91 [ENDPOINT] POST /comments OT226-81 create comments
  controllers/comments.js
  routes/comments.js
  routes/index.js
  schemas/comment.js
  services/comments.js
Labels: endpoint

#95 [ENDPOINT] OT226-82 Add Endpoint Update Comments - PUT /comments /id
  controllers/comments.js
  middlewares/ownerComments.js
  routes/comments.js
  services/comments.js
Labels: endpoint

#98 [FIX] service name, route, and controller
  controllers/news.js
  routes/news.js
  services/news.js
Labels: fix

#101 [DOCUMENTATION] OT226-89 Config Swagger
  package.json
  routes/index.js
  routes/swagger.js
  swagger/config.js
Labels: documentation

#103 [DOCUMENTATION] OT226-90 Add documentation to categories with swagger
  routes/categories.js
Labels: documentation

#109 [DOCUMENTATION] OT226-92 Documentation to members-route
  routes/members.js
Labels: documentation

#112 [TEST] OT226-101 Add Test - Endpoint Authentication
  test/auth.test.js
Labels: test

#114 [TEST] - CONTACTS OT226-100 Endpoint Contacts
  test/contacts.test.js
Labels: test

#116 [TEST] OT226-99 Activities
  test/activities.test.js
Labels: test
